python lpn/train_noise_sched.py \
    --exp_dir exps/celeba/models/ne_lpn/s=scheduled\
    --dataset_config_path exps/celeba/configs/dataset.json \
    --model_config_path exps/celeba/configs/model_ne.json \
    --train_batch_size 64 \
    --dataloader_num_workers 8 \
    --num_steps 40000 \
    --num_steps_pretrain 20000 \
    --pretrain_lr 1e-3 \
    --lr 1e-4 \
    --num_stages 4 \
    --save_every_n_steps 1000 \
    --validate_every_n_steps 1000 \
    --image_size 128 \
    --num_channels 3 \
    --sigma_noise 0.1 \
    --scheduled_noise